<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <AssemblyName>namasdev.Data.Entity.en</AssemblyName>
    <RootNamespace>namasdev.Data.Entity.en</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Deterministic>true</Deterministic>
    <PackageId>namasdev.Data.Entity.en</PackageId>
    <Version>2.0.0</Version>
    <Authors>Matias Alberto Lopez</Authors>
    <Description>namasdev Data Entity library (English)</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <Copyright>2024</Copyright>
    <PackageTags>namasdev</PackageTags>
    <AssemblyVersion>2.0.0</AssemblyVersion>
    <FileVersion>2.0.0</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EntityFramework" Version="6.5.2" />
    <PackageReference Include="namasdev.Data.en" Version="2.0.0" />
  </ItemGroup>

</Project>
