<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <AssemblyName>namasdev.Data.Entity.en</AssemblyName>
    <RootNamespace>namasdev.Data.Entity.en</RootNamespace>
    <Deterministic>true</Deterministic>
    <PackageId>namasdev.Data.Entity.en</PackageId>
    <Version>0.1.0</Version>
    <Authors>Matias Alberto Lopez</Authors>
    <Description>namasdev Data Entity library (English)</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <Copyright>Copyright © 2025 Matias Alberto Lopez</Copyright>
    <PackageTags>namasdev</PackageTags>
    <PackageProjectUrl>https://github.com/MatiasALopez/namasdev.Data.Entity.en</PackageProjectUrl>
    <RepositoryUrl>https://github.com/MatiasALopez/namasdev.Data.Entity.en</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <AssemblyVersion>0.1.0</AssemblyVersion>
    <FileVersion>0.1.0</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EntityFramework" Version="6.5.2" />
    <PackageReference Include="namasdev.Data.en" Version="0.1.0" />
  </ItemGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
